---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-fork
# description will be included in the image's metadata
description: Personal tweaks on top of bazzite-dx

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-dx
# image-version: "stable-42.20250502"
image-version: stable

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # - type: files
  #   files:
  #     - source: system
  #       destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    install:
      - ckb-next 

  # older kernel for rocm
  - type: rpm-ostree
    remove:
      - kernel
      - kernel-core
      - kernel-modules
      - kernel-modules-core
      - kernel-modules-extra
      - kernel-devel
      - kmod-framework-laptop
      - kmod-kvmfr
      - kmod-openrazer
      - kmod-v4l2loopback
      - kmod-wl 
      - kmod-xone
      - kmod-ayaneo-platform
      - kmod-ayn-platform
      - kmod-bmi260
      - kmod-evdi
      - kmod-gcadapter_oc
      - kmod-gpd-fan
      - kmod-nct6687d
      - kmod-ryzen-smu
      - kmod-system76
      - kmod-system76-io
      - kmod-zenergy
    install:
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-107/kernel-devel-matched-6.13.7-107.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-107/kernel-devel-6.13.7-107.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-107/kernel-6.13.7-107.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-107/kernel-core-6.13.7-107.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-107/kernel-modules-6.13.7-107.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-107/kernel-modules-core-6.13.7-107.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-107/kernel-modules-extra-6.13.7-107.bazzite.fc42.x86_64.rpm

  # reinstall bazzite akmods
  - type: akmods
    base: bazzite
    install:
      - framework-laptop
      - kvmfr
      - openrazer
      - v4l2loopback
      - wl
      - xone
      - ayaneo-platform
      - ayn-platform
      - bmi260
      - evdi
      - gcadapter_oc
      - gpd-fan
      - nct6687d
      - ryzen-smu
      - system76
      - system76-io
      - zenergy

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - app.zen_browser.zen
      remove:
        - org.mozilla.firefox
    user: {} # Also add Flathub user repo, but no user packages

  - type: script
    snippets:
      # apply firefox tweaks to zen
      - "sed -i 's/org.mozilla.firefox/app.zen_browser.zen/g' /usr/libexec/bazzite-flatpak-manager" 
      # install lix
      # - "curl -sSf -L https://install.lix.systems/lix | sh -s -- install"

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

