---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-fork
# description will be included in the image's metadata
description: Personal tweaks on top of bazzite-dx

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-dx
# image-version: "stable-42.20250502"
image-version: stable

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common/files.yml

  - type: rpm-ostree
    install:
      - ckb-next 
  
  # rocm is broken on the latest kernel
  - type: rpm-ostree
    remove:
      - kmod-framework-laptop
      - framework-laptop-kmod-common
      - kmod-kvmfr
      - kvmfr
      - kmod-openrazer
      - openrazer-kmod-common
      - kmod-v4l2loopback
      - v4l2loopback
      - akmod-v4l2loopback # ???
      - kmod-wl 
      - kmod-xone
      - xone-kmod-common
      - kmod-ayaneo-platform
      - ayaneo-platform
      - kmod-ayn-platform
      - ayn-platform
      - kmod-bmi260
      - bmi260
      - kmod-gcadapter_oc
      - gcadapter_oc
      - kmod-gpd-fan
      - gpd-fan
      - kmod-nct6687d
      - nct6687d
      - kmod-ryzen-smu
      - ryzen-smu
      - kmod-zenergy
      - zenergy
      - kmod-vhba
      - vhba
      - broadcom-wl

  - type: containerfile
    snippets:
      - COPY --from=ghcr.io/ublue-os/akmods-extra:bazzite-41-6.13.7-108.bazzite.fc41.x86_64 / /tmp/akmods
      - RUN find /tmp/akmods
      - >
        RUN rpm-ostree override replace
        /tmp/akmods/kernel-rpms/*.rpm
      # TODO figure this out
      # - >
      #   RUN dnf install -y 
      #   framework-laptop-kmod-common
      #   kvmfr
      #   openrazer-kmod-common
      #   v4l2loopback
      #   xone-kmod-common
      #   ayaneo-platform
      #   ayn-platform
      #   bmi260
      #   gcadapter_oc
      #   gpd-fan
      #   nct6687d
      #   ryzen-smu
      #   zenergy
      #   vhba
      #   broadcom-wl
      #   /tmp/akmods/rpms/kmods/*.rpm

  - from-file: common/files.yml
  - from-file: common/zen.yml
  - from-file: common/scripts.yml
  - from-file: common/services.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

